### ISSUE TITLE
DELETED

### ISSUE THREAD

**Issue by Mrcomputer1** [quat1024/FixNameColors#1]
DELETED

**Content was:**
`Server s;` is not what is normally used (that I know) it normally is just using Bukkit. instead of creating a server variable

and the

``` java
public FixNameColorPlugin() {

}
```

is not needed

Still the plugin is really useful and I guess those things aren't really important

**Comment by quat1024** [comment]
Thanks for the programming tips. I used a constructor because I got weird errors about "Missing constructor" until I added a dummy one (that's java for you). & I like to use variables to save space :)

**Comment by Mrcomputer1** [comment]
@quat1024 Ok
